"""Add unlock_attempts and is_replaced to Message model

Revision ID: 1ab6e9a617a3
Revises: c44d8c5bb3f3
Create Date: 2025-06-07 14:53:05.932978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ab6e9a617a3'
down_revision = 'c44d8c5bb3f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unlock_attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_replaced', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('is_replaced')
        batch_op.drop_column('unlock_attempts')

    # ### end Alembic commands ###
