"""Add password_hash column to User model

Revision ID: 678015bc9630
Revises: 
Create Date: 2025-06-03 10:47:16.043574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '678015bc9630'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=False, server_default='default_hash'))

    # Note: SQLite doesn't support ALTER COLUMN to drop defaults, but that's okay
    # The default is only used during migration and won't affect new rows
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=128), nullable=False))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
